fastlane_version "2.27.0"
default_platform :ios

platform :ios do
  before_all do
    ENV["FASTLANE_EXPLICIT_OPEN_SIMULATOR"] = "2"
    clear_derived_data
  end

  lane :unit_test do
    scan(
      code_coverage: true,
      scheme:  'CucumberSwift',
      project: 'CucumberSwift.xcodeproj'
    )
  end

  lane :build_swiftpm do
    spm(
      command: "build",
      build_path: "./build",
      configuration: "release"
    )
  end

  lane :cocoapods_liblint do
    pod_lib_lint(podspec: 'CucumberSwift.podspec', allow_warnings: true)
  end
end
